# Generated by Django 4.1.3 on 2022-12-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("number", models.CharField(max_length=100)),
                ("prichina", models.CharField(max_length=100)),
                ("date", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Forchildren",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("price", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="Forman",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("price", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(null=True, upload_to="")),
                ("image_advices", models.ImageField(null=True, upload_to="")),
                ("image_advices1", models.ImageField(null=True, upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="Slaider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="")),
                ("image1", models.ImageField(upload_to="")),
                ("image2", models.ImageField(upload_to="")),
                ("number", models.CharField(max_length=100)),
            ],
        ),
    ]
