# Generated by Django 4.1.3 on 2022-12-20 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_stick"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Stick",
        ),
    ]
