# Generated by Django 4.1.3 on 2022-12-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_delete_stick"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inai",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="")),
                ("text", models.TextField(max_length=1000)),
            ],
        ),
    ]
