# Generated by Django 4.1.3 on 2022-12-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_inai"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inai",
            old_name="text",
            new_name="title",
        ),
        migrations.AddField(
            model_name="inai",
            name="descriptions",
            field=models.TextField(default=1, max_length=3000),
            preserve_default=False,
        ),
    ]
