# Generated by Django 4.1.3 on 2022-12-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_rename_text_inai_title_inai_descriptions"),
    ]

    operations = [
        migrations.CreateModel(
            name="Foot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=200)),
                ("text", models.TextField(max_length=3000)),
            ],
        ),
    ]
