# Generated by Django 4.1.3 on 2022-12-22 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
